export enum EventType {
  BOOKING_CREATED = "BOOKING_CREATED",
  BOOKING_APPROVED = "BOOKING_APPROVED",
  BOOKING_REJECTED = "BOOKING_REJECTED",
  BOOKING_CANCELLED = "BOOKING_CANCELLED",
  USER_REGISTERED = "USER_REGISTERED",
  USER_ACTIVATED = "USER_ACTIVATED",
}